function init(self)
	msg.post(".", "acquire_input_focus")
end

function update(self, dt)
end

function on_input(self, action_id, action)
	local p = go.get_position()
	if action_id == hash("up") then
		p.y = p.y + 1
	elseif action_id == hash("down") then
		p.y = p.y - 1
	elseif action_id == hash("left") then
		p.x = p.x - 1
	elseif action_id == hash("right") then
		p.x = p.x + 1
	elseif action_id == hash("click") and action.pressed then
		p.y = p.y + 1
	end
	go.set_position(p)
	-- print(p)
end